# This file is a template, and might need editing before it works on your project.
---
# image
# image: swr.cn-north-4.myhuaweicloud.com/codechina/vuepress:1.8.2
image: vuepress:1.8.2

#before_script:
#  - apk add --update --no-cache git

#variables:
#  GIT_SUBMODULE_STRATEGY: recursive
 
pages:
  script:
    - export NODE_OPTIONS=--max_old_space_size=4096
    - npm config set registry https://registry.npm.taobao.org
    - npm i
    - vuepress build docs -d public
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - pages
