# This file is a template, and might need editing before it works on your project.
---
# image
#image: swr.cn-north-4.myhuaweicloud.com/codechina/vuepress:latest
image: vuepress:latest

#before_script:
#  - apk add --update --no-cache git
 
 
#variables:
#  GIT_SUBMODULE_STRATEGY: recursive
 
pages:
  script:
    - npm i
    - vuepress build docs -d public
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - pages
