name: 'github actions build and deploy gh-pages'
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: install and build
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: git@github.com:binghe001/binghe001.github.io.git
          BRANCH: master
          FOLDER: docs/.vuepress/dist
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}