name: 'github actions build and deploy gh-pages'
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: install and build
        run: |
          npm install
          npm run build
          cp README.md .site/
      - name: "Deploy Github"
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: git@github.com:binghe001/binghe001.github.io.git
          BRANCH: master
          FOLDER: .site
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      - name: "Deploy Gitee"
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: git@gitee.com:binghe001/binghe001.gitee.io.git
          BRANCH: master
          FOLDER: .site
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_GITEE_PRIVATE_KEY }}
          KNOWN_HOSTS_FILE: docs/hosts/known_hosts